### ISSUE TITLE
Run Pod Install Failed

### ISSUE THREAD

**Issue by quangphananh** [bratan/flutter_device_locale#4]
When I Run Pod Install the following issue: (use latest version 0.3.4+1)
- `flutter_device_locale` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by harimayco** [comment]
I have the same problem, is there any fix for this?

**Comment by bratan** [comment]
There are some issues with Flutter plugins using Swift, basically additional steps need to be taken when using them.

In the next couple of days I`m going to replace the Swift code with Objective-C and the issue will be fixed.

**Comment by achernoprudov** [comment]
Workaround: set the Swift version by including `ENV['SWIFT_VERSION'] = '5'` at the top of your `Podfile`.
