### ISSUE TITLE
Web and desktop support?

### ISSUE THREAD

**Issue by liudonghua123** [bratan/flutter_device_locale#8]
I try to use flutter_translate package which depend on this plugin, I hope it can support web and/or desktop support. Then a lot of devices can use this package.

**Comment by liudonghua123** [comment]
I see https://github.com/bratan/flutter_device_locale/pull/7 is merged, now the web is supported.

**Comment by bratan** [comment]
@liudonghua123 - Yes, web is now supported.

**Comment by nohli** [comment]
After specifying

```
environment:
  sdk: '>=2.9.0 <3.0.0'
```

in `pubspec.yaml`, the automatically generated file generated_plugin_registrant.dart leads to an analyzer problem:

> Don't import implementation files from another package.

(https://dart-lang.github.io/linter/lints/implementation_imports.html)

because it imports a file from this package's `src` folder:

```
//
// Generated file. Do not edit.
//

// ignore: unused_import
import 'dart:ui';

import 'package:flutter_device_locale/src/web.dart'; // <- HERE
import 'package:shared_preferences_web/shared_preferences_web.dart';
import 'package:url_launcher_web/url_launcher_web.dart';

import 'package:flutter_web_plugins/flutter_web_plugins.dart';

// ignore: public_member_api_docs
void registerPlugins(PluginRegistry registry) {
  FlutterDeviceLocaleWebPlugin.registerWith(
      registry.registrarFor(FlutterDeviceLocaleWebPlugin));
  SharedPreferencesPlugin.registerWith(
      registry.registrarFor(SharedPreferencesPlugin));
  UrlLauncherPlugin.registerWith(registry.registrarFor(UrlLauncherPlugin));
  registry.registerMessageHandler();
}
```

Can this be fixed?

**Comment by MyBuzzTechnologies** [comment]
Is desktop support planned for this? I use flutter_translate which depends on this package but I can't build MacOS or Windows desktop apps because this package doesn't support it.

**Comment by srix55** [comment]
Would be great with desktop support. Not sure if that's a lot of work. Currently nothing is out there for getting desktop locales.

**Comment by bratan** [comment]
Since version 3.0 flutter_translate doesn't depend on this package anymore, in order to support all platforms, including desktop.

I don't plan on implementing desktop support anytime soon for this package but feel free to submit a PR.

**Comment by srix55** [comment]
@bratan I would like to contribute towards desktop support. Would I be close if I said it's about 100-150 hr effort for a flutter enthusiast? I mean... if you have to make a wild guess...

**Comment by bratan** [comment]
@srix55 - Much less I think, but it depends on your experience with each platform.

**Comment by srix55** [comment]
@bratan Thanks. I'll see what I can do.
